-- Reviewed Mystora admin foundation.
-- Apply to project nphpncgggkwckfhyzlwt only after explicit production approval.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role text not null default 'editor' check (role in ('owner', 'manager', 'editor')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
comment on table public.admin_users is 'Invite-only Mystora staff authorization records.';
alter table public.admin_users enable row level security;

create or replace function private.is_admin(
  allowed_roles text[] default array['owner','manager','editor']::text[]
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1 from public.admin_users au
      where au.user_id = (select auth.uid())
        and au.active is true
        and au.role = any(allowed_roles)
    );
$$;
revoke all on function private.is_admin(text[]) from public;
grant execute on function private.is_admin(text[]) to authenticated;

create policy "Staff can view own admin profile"
on public.admin_users for select to authenticated
using (user_id = (select auth.uid()) or private.is_admin(array['owner']::text[]));
create policy "Owners can create staff profiles"
on public.admin_users for insert to authenticated
with check (private.is_admin(array['owner']::text[]));
create policy "Owners can update staff profiles"
on public.admin_users for update to authenticated
using (private.is_admin(array['owner']::text[]))
with check (private.is_admin(array['owner']::text[]));
create policy "Owners can delete staff profiles"
on public.admin_users for delete to authenticated
using (private.is_admin(array['owner']::text[]));

alter table public.products
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists updated_by uuid references auth.users(id) on delete set null;

create unique index if not exists products_slug_unique_ci
  on public.products (lower(slug)) where slug is not null;

alter table public.products
  add constraint products_name_required check (name is not null and btrim(name) <> ''),
  add constraint products_slug_format check (slug is not null and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  add constraint products_nonnegative_values check (
    coalesce(price, 0) >= 0
    and coalesce(price_10ml, 0) >= 0
    and coalesce(price_50ml, 0) >= 0
    and coalesce(price_100ml, 0) >= 0
    and coalesce(stock, 0) >= 0
  );

create policy "Admins can view all products"
on public.products for select to authenticated using (private.is_admin());
create policy "Admins can create products"
on public.products for insert to authenticated with check (private.is_admin());
create policy "Admins can update products"
on public.products for update to authenticated
using (private.is_admin()) with check (private.is_admin());
create policy "Managers can delete products"
on public.products for delete to authenticated
using (private.is_admin(array['owner','manager']::text[]));

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (btrim(name) <> ''),
  description text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
alter table public.collections enable row level security;

create table if not exists public.collection_products (
  collection_id bigint not null references public.collections(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now(),
  primary key (collection_id, product_id)
);
alter table public.collection_products enable row level security;

create policy "Public can view active collections"
on public.collections for select to anon, authenticated using (active is true);
create policy "Admins can view all collections"
on public.collections for select to authenticated using (private.is_admin());
create policy "Admins can create collections"
on public.collections for insert to authenticated with check (private.is_admin());
create policy "Admins can update collections"
on public.collections for update to authenticated
using (private.is_admin()) with check (private.is_admin());
create policy "Managers can delete collections"
on public.collections for delete to authenticated
using (private.is_admin(array['owner','manager']::text[]));

create policy "Public can view active collection products"
on public.collection_products for select to anon, authenticated
using (
  exists (select 1 from public.collections c where c.id = collection_id and c.active is true)
  and exists (select 1 from public.products p where p.id = product_id and p.active is true)
);
create policy "Admins can view all collection products"
on public.collection_products for select to authenticated using (private.is_admin());
create policy "Admins can create collection products"
on public.collection_products for insert to authenticated with check (private.is_admin());
create policy "Admins can update collection products"
on public.collection_products for update to authenticated
using (private.is_admin()) with check (private.is_admin());
create policy "Admins can delete collection products"
on public.collection_products for delete to authenticated using (private.is_admin());

create table if not exists public.site_settings (
  key text primary key check (key ~ '^[a-z0-9_]+$'),
  value jsonb not null default 'null'::jsonb,
  public boolean not null default false,
  description text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
alter table public.site_settings enable row level security;

create policy "Public can read public settings"
on public.site_settings for select to anon, authenticated using (public is true);
create policy "Admins can view all settings"
on public.site_settings for select to authenticated using (private.is_admin());
create policy "Managers can create settings"
on public.site_settings for insert to authenticated
with check (private.is_admin(array['owner','manager']::text[]));
create policy "Managers can update settings"
on public.site_settings for update to authenticated
using (private.is_admin(array['owner','manager']::text[]))
with check (private.is_admin(array['owner','manager']::text[]));
create policy "Owners can delete settings"
on public.site_settings for delete to authenticated
using (private.is_admin(array['owner']::text[]));

alter table public.orders
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists product_id bigint references public.products(id) on delete set null,
  add column if not exists size text,
  add column if not exists email text,
  add column if not exists address text,
  add column if not exists customer_notes text,
  add column if not exists admin_notes text,
  add column if not exists source text not null default 'manual',
  add column if not exists assigned_to uuid references auth.users(id) on delete set null,
  add column if not exists updated_by uuid references auth.users(id) on delete set null;

update public.orders set status = 'new' where status is null or status = 'pending';
alter table public.orders
  alter column status set default 'new',
  alter column status set not null,
  add constraint orders_status_allowed check (
    status in ('new','contacted','confirmed','preparing','dispatched','completed','cancelled')
  ),
  add constraint orders_nonnegative_total check (coalesce(total, 0) >= 0),
  add constraint orders_size_allowed check (size is null or size in ('10ml','50ml','100ml'));

create policy "Admins can view orders"
on public.orders for select to authenticated using (private.is_admin());
create policy "Admins can create orders"
on public.orders for insert to authenticated with check (private.is_admin());
create policy "Admins can update orders"
on public.orders for update to authenticated
using (private.is_admin()) with check (private.is_admin());
create policy "Managers can delete orders"
on public.orders for delete to authenticated
using (private.is_admin(array['owner','manager']::text[]));

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
create policy "Admins can view audit logs"
on public.audit_logs for select to authenticated using (private.is_admin());

create or replace function private.touch_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  if to_jsonb(new) ? 'updated_by' then new.updated_by = (select auth.uid()); end if;
  return new;
end;
$$;
revoke all on function private.touch_updated_at() from public, anon, authenticated;

create or replace function private.record_admin_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  target_id text;
  payload jsonb;
begin
  if (select auth.uid()) is null then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;
  target_id := coalesce(
    to_jsonb(new)->>'id', to_jsonb(old)->>'id',
    to_jsonb(new)->>'key', to_jsonb(old)->>'key',
    to_jsonb(new)->>'user_id', to_jsonb(old)->>'user_id'
  );
  payload := jsonb_strip_nulls(jsonb_build_object(
    'old', case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    'new', case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  ));
  insert into public.audit_logs(actor_id, action, entity_type, entity_id, details)
  values ((select auth.uid()), lower(tg_op), tg_table_name, target_id, payload);
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;
revoke all on function private.record_admin_change() from public, anon, authenticated;

create trigger products_touch_updated_at before update on public.products
for each row execute function private.touch_updated_at();
create trigger collections_touch_updated_at before update on public.collections
for each row execute function private.touch_updated_at();
create trigger settings_touch_updated_at before update on public.site_settings
for each row execute function private.touch_updated_at();
create trigger orders_touch_updated_at before update on public.orders
for each row execute function private.touch_updated_at();
create trigger admin_users_touch_updated_at before update on public.admin_users
for each row execute function private.touch_updated_at();

create trigger products_audit after insert or update or delete on public.products
for each row execute function private.record_admin_change();
create trigger collections_audit after insert or update or delete on public.collections
for each row execute function private.record_admin_change();
create trigger collection_products_audit after insert or update or delete on public.collection_products
for each row execute function private.record_admin_change();
create trigger settings_audit after insert or update or delete on public.site_settings
for each row execute function private.record_admin_change();
create trigger orders_audit after insert or update or delete on public.orders
for each row execute function private.record_admin_change();
create trigger admin_users_audit after insert or update or delete on public.admin_users
for each row execute function private.record_admin_change();

insert into public.collections (slug, name, description, active, sort_order) values
  ('new-arrivals', 'New Arrivals', 'The newest additions to Mystora.', true, 10),
  ('special-collection', 'Special Collection', 'Mystora signature and limited fragrances.', true, 20),
  ('decants', 'Decants', 'Explore every fragrance in a 10 ml format.', true, 30);

insert into public.collection_products (collection_id, product_id, position)
select c.id, p.id, row_number() over (order by p.created_at desc, p.id desc)::integer - 1
from public.collections c cross join public.products p where c.slug = 'new-arrivals';
insert into public.collection_products (collection_id, product_id, position)
select c.id, p.id, row_number() over (order by p.id)::integer - 1
from public.collections c cross join public.products p
where c.slug = 'special-collection' and p.category = 'special';
insert into public.collection_products (collection_id, product_id, position)
select c.id, p.id, row_number() over (order by p.id)::integer - 1
from public.collections c cross join public.products p
where c.slug = 'decants' and p.price_10ml is not null;

insert into public.site_settings (key, value, public, description) values
  ('whatsapp_phone', to_jsonb('94768253595'::text), true, 'WhatsApp ordering number.'),
  ('facebook_url', to_jsonb('https://www.facebook.com/profile.php?id=61581027238674'::text), true, 'Official Facebook profile.'),
  ('instagram_url', to_jsonb(''::text), true, 'Official Instagram profile.'),
  ('tiktok_url', to_jsonb(''::text), true, 'Official TikTok profile.'),
  ('announcement', to_jsonb(''::text), true, 'Optional storefront announcement.'),
  ('delivery_note', to_jsonb('Islandwide delivery across Sri Lanka.'::text), true, 'Delivery note.');

grant select, insert, update, delete on public.admin_users to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select on public.collections, public.collection_products, public.site_settings to anon;
grant select, insert, update, delete on public.collections, public.collection_products, public.site_settings to authenticated;
grant select, insert, update, delete on public.orders to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "Admins can list product media"
on storage.objects for select to authenticated
using (bucket_id = 'images' and private.is_admin());
create policy "Admins can upload product media"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'images' and private.is_admin()
  and lower(storage.extension(name)) = any(array['jpg','jpeg','png','webp'])
);
create policy "Admins can update product media"
on storage.objects for update to authenticated
using (bucket_id = 'images' and private.is_admin())
with check (
  bucket_id = 'images' and private.is_admin()
  and lower(storage.extension(name)) = any(array['jpg','jpeg','png','webp'])
);
create policy "Managers can delete product media"
on storage.objects for delete to authenticated
using (
  bucket_id = 'images'
  and private.is_admin(array['owner','manager']::text[])
);

-- Supabase projects with legacy automatic grants require an explicit
-- least-privilege reset. Keep this in the foundation for fresh deployments.
revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;
revoke all on table public.collections from anon, authenticated;
revoke all on table public.collection_products from anon, authenticated;
revoke all on table public.site_settings from anon, authenticated;
grant select, insert, update, delete on public.admin_users to authenticated;
grant select on public.audit_logs to authenticated;
grant select on public.collections, public.collection_products, public.site_settings to anon;
grant select, insert, update, delete on public.collections, public.collection_products, public.site_settings to authenticated;
revoke all on all sequences in schema public from anon;

create index if not exists admin_users_updated_by_idx on public.admin_users(updated_by);
create index if not exists audit_logs_actor_id_idx on public.audit_logs(actor_id);
create index if not exists collection_products_product_id_idx on public.collection_products(product_id);
create index if not exists collections_updated_by_idx on public.collections(updated_by);
create index if not exists orders_assigned_to_idx on public.orders(assigned_to);
create index if not exists orders_product_id_idx on public.orders(product_id);
create index if not exists orders_updated_by_idx on public.orders(updated_by);
create index if not exists products_updated_by_idx on public.products(updated_by);
create index if not exists site_settings_updated_by_idx on public.site_settings(updated_by);
create index if not exists orders_status_updated_at_idx on public.orders(status, updated_at desc);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
